### ISSUE TITLE
how to use? hard to understand readMe.md

### ISSUE THREAD

**Issue by liushiniuniu** [hazzard993/LuaToTypeScript#1]
i have cloned project into my computer, but command "yarn global lua-to-typescript"  did not work. it's hard to understand the useStep. can you update the readMe.md?

**Comment by hazzard993** [comment]
Hello! Haven't actually released a version yet as it isn't ready for a CLI. That'll be coming up in the next day or two

**Comment by hazzard993** [comment]
Ok looks like it is ready now. Give the code below a shot

```sh
yarn global add lua-to-typescript
ltts main.lua
# Creates main.ts
```
