### ISSUE TITLE
It throws exception on me. Did I miss anything?

### ISSUE THREAD

**Issue by sf6472** [hazzard993/LuaToTypeScript#22]
![image](https://user-images.githubusercontent.com/56741965/184857627-aa6426f9-6edf-4faa-92d4-25fe39bc4a51.png)

**Comment by hazzard993** [comment]
Thanks for the report!

Looks like it was an inconsistency in the AST that was not expected

```lua
fn{} -- { arguments: "..." }
fn"" -- { argument: "..." }
```

Should be fixed in `lua-to-typescript@0.2.2` now
